version: "3"
services:
  cosmetics:
    image: registry.digitalocean.com/polusgg/server-cosmetics
    # Environment variables
    environment:
      DATABASE_URL: "mongodb+srv://cosmetics:*@mongodb-cosmetics-8f2c7601.mongo.ondigitalocean.com/pgg-cosmetics?authSource=admin&replicaSet=mongodb-cosmetics"
      CA_CERT_PATH: "./ca-certificate-pggcosmetics.crt"
      STEAM_PUBLISHER_KEY: "secret"
      ACCOUNT_AUTH_TOKEN: "secret"
